[package]
name = "pikachu"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pikachu"
path = "src/prover/prover.rs"

[dependencies]
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-poly = "0.4.2"
ark-serialize = "0.4.2"
ark-bn254 = "0.4.0"
ark-std = "0.4.0"
hex = "0.4.3"
serde_json = "1.0.128"
